### ISSUE TITLE
Require 'dronestream' missing

### ISSUE THREAD

**Issue by krohne** [daraosn/oculus-drone#2]
index.coffee: 
Add a line for
dronestream = require "dronestream"

**Comment by daraosn** [comment]
AHA – The last line of index.coffee includes:
require("dronestream")...

So, it's not missing there, but in the dependencies of package.json, I'll add it asap.

**Comment by krohne** [comment]
When I built from scratch, node.js complained about a missing dronestream module. I got it working when I added the line to my copy of index.coffee, but I see now that it's package.json which should require dronestream.

**Comment by MyifanW** [comment]
So what do you put in the package?

**Comment by daraosn** [comment]
@MyifanW  please pull the new code and run `npm install` again

**Comment by krohne** [comment]
I tried that (wiped all of the code and ran 'npm install' from clean). After a few more adjustments (at least one package file is deprecated in bootstrap or faye or something), and finally got everything running without errors. I get feedback from the Oculus Rift. The Chrome page says I'm connected to the OR and the AR drone without error (no console errors), but I get no video and the drone doesn't respond to commands. I'm going  to try some of the suggestions in this thread next:
https://github.com/eschnou/ardrone-webflight/issues/33
For example, I had the same problem (briefly) with bower installing everything to './bower_components' instead of './components).
On another drone-video project, I read that the latest version of Chrome may not be compatible with the video streaming library, so I may need to change package.json to require an updated version of some things.
I'm running on Windows 7, and it's possible this project will work properly if I run in a Linux VM.
