### ISSUE TITLE
bootstrap: wrong path

### ISSUE THREAD

**Issue by krohne** [daraosn/oculus-drone#4]
Browser console log reports:

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/components/bootstrap/css/bootstrap.min.css
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/components/bootstrap/js/bootstrap.min.js

Missing components are installed in 
/bower_components/bootstrap.css/css/bootstrap.min.css
/bower_components/bootstrap.css/js/bootstrap.min.js

**Comment by daraosn** [comment]
Ok, I was using an old version of bower, now it's up-to-date. Still should update the deprecated component.json and its components  (issue #3), but I'm out of time at the moment, if you want to contribute I'd appreciate it.

**Comment by krohne** [comment]
I'm new to GitHub, but sure; it's about time I learned how to contribute back to the project.
