### ISSUE TITLE
Images do not render

### ISSUE THREAD

**Issue by krohne** [daraosn/oculus-drone#5]
The video feed seems to be updating in Chrome. I get continuously updating image elements at:

xpath: //*[@id="drones"]/div/div[2]/img

html: <img src="/drone/camera/1/0.7244175877422094">

However, the video images render as the broken-image icon in Chrome (v34)

**Comment by daraosn** [comment]
Yes, this image is not supposed to load, as I wrote on the README file, this is a fork from another project that uses image feed from several drones in the same network, this image is not being used at the moment, as this project works only for one drone and uses a ffmpeg video feed instead. Use the key 'O' and go full-screen to activate the oculus interface.
